"project_identifier" : "winsparkle"
"base_path" : "translations"
"preserve_hierarchy" : false

"files" : [
  {
    "source" : "/winsparkle.pot",
    "translation" : "/%locale_with_underscore%.po",
    "languages_mapping" : {
      "locale_with_underscore" : {
        "af": "af",
        "ar": "ar",
        "be": "be",
        "bg": "bg",
        "bs": "bs",
        "co": "co",
        "cs": "cs",
        "da": "da",
        "de": "de",
        "el": "el",
        "es-ES": "es",
        "et": "et",
        "eu": "eu",
        "fr": "fr",
        "ga-IE": "ga",
        "he": "he",
        "hy-AM": "hy",
        "hr": "hr",
        "hu": "hu",
        "id": "id",
        "is": "is",
        "it": "it",
        "ja": "ja",
        "ko": "ko",
        "kk": "kk",
        "lt": "lt",
        "nb": "nb",
        "nl": "nl",
        "pl": "pl",
        "ru": "ru",
        "sk": "sk",
        "sr": "sr",
        "sv-SE": "sv",
        "th": "th",
        "tr": "tr",
        "uk": "uk",
        "zh-CN": "zh_CN",
        "zh-TW": "zh_TW"
      }
    }
  }
]
