<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup />
  <ItemDefinitionGroup>
    <ClCompile>
        <LanguageStandard>stdcpp17</LanguageStandard>
        <AdditionalIncludeDirectories>
            $(MSBuildThisFileDirectory)include;
            $(MSBuildThisFileDirectory)3rdparty\config;
            $(MSBuildThisFileDirectory)3rdparty\expat\expat\lib;
            $(MSBuildThisFileDirectory)3rdparty\ed25519\src;
            $(MSBuildThisFileDirectory)3rdparty\libtommath;
            $(MSBuildThisFileDirectory)3rdparty\wxWidgets\include;
            %(AdditionalIncludeDirectories)
      </AdditionalIncludeDirectories>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemGroup />
</Project>