[{"title":"BugVersion","href":"WinSparkle.BugVersion.htm"}
,{"title":"callbackFuncs","href":"WinSparkle.callbackFuncs.htm"}
,{"title":"callbackProcs","href":"WinSparkle.callbackProcs.htm"}
,{"title":"DoOnCanShutdown","href":"WinSparkle.DoOnCanShutdown.htm"}
,{"title":"DoOnError","href":"WinSparkle.DoOnError.htm"}
,{"title":"DoOnShutDown","href":"WinSparkle.DoOnShutDown.htm"}
,{"title":"DoOnUpdateCancelled","href":"WinSparkle.DoOnUpdateCancelled.htm"}
,{"title":"DoOnUpdateFound","href":"WinSparkle.DoOnUpdateFound.htm"}
,{"title":"DoOnUpdateNotFound","href":"WinSparkle.DoOnUpdateNotFound.htm"}
,{"title":"Form4","href":"Unit4.Form4.htm"}
,{"title":"MajorVersion","href":"WinSparkle.MajorVersion.htm"}
,{"title":"MinorVersion","href":"WinSparkle.MinorVersion.htm"}
,{"title":"Project3","href":"Project3.htm"}
,{"title":"TCallbackArray","href":"WinSparkle.TCallbackArray.htm"}
,{"title":"TCallbackArrayFunctions","href":"WinSparkle.TCallbackArrayFunctions.htm"}
,{"title":"TCallbackType","href":"WinSparkle.TCallbackType.htm"}
,{"title":"TCallbackType.cbDidFindUpdate","href":"WinSparkle.TCallbackType.htm"}
,{"title":"TCallbackType.cbDidNotFindUpdate","href":"WinSparkle.TCallbackType.htm"}
,{"title":"TCallbackType.cbError","href":"WinSparkle.TCallbackType.htm"}
,{"title":"TCallbackType.cbShutdown","href":"WinSparkle.TCallbackType.htm"}
,{"title":"TCallbackType.cbUpdateCancelled","href":"WinSparkle.TCallbackType.htm"}
,{"title":"TCallbackTypeFunc","href":"WinSparkle.TCallbackTypeFunc.htm"}
,{"title":"TCallbackTypeFunc.cbCanShutdown","href":"WinSparkle.TCallbackTypeFunc.htm"}
,{"title":"TForm4","href":"Unit4.TForm4.htm"}
,{"title":"TForm4.Button1","href":"Unit4.TForm4.Button1.htm"}
,{"title":"TForm4.Button1Click(TObject)","href":"Unit4.TForm4.Button1Click.htm"}
,{"title":"TForm4.Button2","href":"Unit4.TForm4.Button2.htm"}
,{"title":"TForm4.Button2Click(TObject)","href":"Unit4.TForm4.Button2Click.htm"}
,{"title":"TForm4.Button3","href":"Unit4.TForm4.Button3.htm"}
,{"title":"TForm4.Button3Click(TObject)","href":"Unit4.TForm4.Button3Click.htm"}
,{"title":"TForm4.Button4","href":"Unit4.TForm4.Button4.htm"}
,{"title":"TForm4.Button4Click(TObject)","href":"Unit4.TForm4.Button4Click.htm"}
,{"title":"TForm4.Button5","href":"Unit4.TForm4.Button5.htm"}
,{"title":"TForm4.Button5Click(TObject)","href":"Unit4.TForm4.Button5Click.htm"}
,{"title":"TForm4.Button6","href":"Unit4.TForm4.Button6.htm"}
,{"title":"TForm4.Button6Click(TObject)","href":"Unit4.TForm4.Button6Click.htm"}
,{"title":"TForm4.Button7","href":"Unit4.TForm4.Button7.htm"}
,{"title":"TForm4.Button7Click(TObject)","href":"Unit4.TForm4.Button7Click.htm"}
,{"title":"TForm4.Button8","href":"Unit4.TForm4.Button8.htm"}
,{"title":"TForm4.Button8Click(TObject)","href":"Unit4.TForm4.Button8Click.htm"}
,{"title":"TForm4.Button9","href":"Unit4.TForm4.Button9.htm"}
,{"title":"TForm4.Button9Click(TObject)","href":"Unit4.TForm4.Button9Click.htm"}
,{"title":"TForm4.CheckBox1","href":"Unit4.TForm4.CheckBox1.htm"}
,{"title":"TForm4.CheckBox1Change(TObject)","href":"Unit4.TForm4.CheckBox1Change.htm"}
,{"title":"TForm4.CheckBox2","href":"Unit4.TForm4.CheckBox2.htm"}
,{"title":"TForm4.CheckBox3","href":"Unit4.TForm4.CheckBox3.htm"}
,{"title":"TForm4.CheckBox4","href":"Unit4.TForm4.CheckBox4.htm"}
,{"title":"TForm4.CheckBox5","href":"Unit4.TForm4.CheckBox5.htm"}
,{"title":"TForm4.Circle1","href":"Unit4.TForm4.Circle1.htm"}
,{"title":"TForm4.Edit1","href":"Unit4.TForm4.Edit1.htm"}
,{"title":"TForm4.Edit2","href":"Unit4.TForm4.Edit2.htm"}
,{"title":"TForm4.Edit3","href":"Unit4.TForm4.Edit3.htm"}
,{"title":"TForm4.Edit4","href":"Unit4.TForm4.Edit4.htm"}
,{"title":"TForm4.Edit5","href":"Unit4.TForm4.Edit5.htm"}
,{"title":"TForm4.FormCreate(TObject)","href":"Unit4.TForm4.FormCreate.htm"}
,{"title":"TForm4.FormDestroy(TObject)","href":"Unit4.TForm4.FormDestroy.htm"}
,{"title":"TForm4.GroupBox1","href":"Unit4.TForm4.GroupBox1.htm"}
,{"title":"TForm4.GroupBox2","href":"Unit4.TForm4.GroupBox2.htm"}
,{"title":"TForm4.Label1","href":"Unit4.TForm4.Label1.htm"}
,{"title":"TForm4.Label10","href":"Unit4.TForm4.Label10.htm"}
,{"title":"TForm4.Label2","href":"Unit4.TForm4.Label2.htm"}
,{"title":"TForm4.Label3","href":"Unit4.TForm4.Label3.htm"}
,{"title":"TForm4.Label4","href":"Unit4.TForm4.Label4.htm"}
,{"title":"TForm4.Label5","href":"Unit4.TForm4.Label5.htm"}
,{"title":"TForm4.Label6","href":"Unit4.TForm4.Label6.htm"}
,{"title":"TForm4.Label7","href":"Unit4.TForm4.Label7.htm"}
,{"title":"TForm4.Label8","href":"Unit4.TForm4.Label8.htm"}
,{"title":"TForm4.Label9","href":"Unit4.TForm4.Label9.htm"}
,{"title":"TForm4.PopupBox1","href":"Unit4.TForm4.PopupBox1.htm"}
,{"title":"TForm4.RadioButton1","href":"Unit4.TForm4.RadioButton1.htm"}
,{"title":"TForm4.RadioButton2","href":"Unit4.TForm4.RadioButton2.htm"}
,{"title":"TForm4.RadioButton3","href":"Unit4.TForm4.RadioButton3.htm"}
,{"title":"TForm4.Rectangle1","href":"Unit4.TForm4.Rectangle1.htm"}
,{"title":"TUpdateType","href":"WinSparkle.TUpdateType.htm"}
,{"title":"TUpdateType.utWithoutUI","href":"WinSparkle.TUpdateType.htm"}
,{"title":"TUpdateType.utWithUI","href":"WinSparkle.TUpdateType.htm"}
,{"title":"TUpdateType.utWithUIAndInstall","href":"WinSparkle.TUpdateType.htm"}
,{"title":"TWinSparkle","href":"WinSparkle.TWinSparkle.htm"}
,{"title":"TWinSparkle.AppBuildVersion","href":"WinSparkle.TWinSparkle.AppBuildVersion.htm"}
,{"title":"TWinSparkle.AppcastURL","href":"WinSparkle.TWinSparkle.AppcastURL.htm"}
,{"title":"TWinSparkle.AutoCheckForUpdates","href":"WinSparkle.TWinSparkle.AutoCheckForUpdates.htm"}
,{"title":"TWinSparkle.CheckUpdate(TUpdateType)","href":"WinSparkle.TWinSparkle.CheckUpdate.htm"}
,{"title":"TWinSparkle.CheckUpdateWithoutUI","href":"WinSparkle.TWinSparkle.CheckUpdateWithoutUI.htm"}
,{"title":"TWinSparkle.CheckUpdateWithUI","href":"WinSparkle.TWinSparkle.CheckUpdateWithUI.htm"}
,{"title":"TWinSparkle.CheckUpdateWithUIandInstall","href":"WinSparkle.TWinSparkle.CheckUpdateWithUIandInstall.htm"}
,{"title":"TWinSparkle.Cleanup","href":"WinSparkle.TWinSparkle.Cleanup.htm"}
,{"title":"TWinSparkle.Create","href":"WinSparkle.TWinSparkle.Create.htm"}
,{"title":"TWinSparkle.Create(string)","href":"WinSparkle.TWinSparkle.Create(string).htm"}
,{"title":"TWinSparkle.Destroy","href":"WinSparkle.TWinSparkle.Destroy.htm"}
,{"title":"TWinSparkle.DLLLoaded","href":"WinSparkle.TWinSparkle.DLLLoaded.htm"}
,{"title":"TWinSparkle.DLLPath","href":"WinSparkle.TWinSparkle.DLLPath.htm"}
,{"title":"TWinSparkle.Init","href":"WinSparkle.TWinSparkle.Init.htm"}
,{"title":"TWinSparkle.LastCheckTime","href":"WinSparkle.TWinSparkle.LastCheckTime.htm"}
,{"title":"TWinSparkle.OnCanShutDown","href":"WinSparkle.TWinSparkle.OnCanShutDown.htm"}
,{"title":"TWinSparkle.OnDidFindUpdate","href":"WinSparkle.TWinSparkle.OnDidFindUpdate.htm"}
,{"title":"TWinSparkle.OnDidNotFindUpdate","href":"WinSparkle.TWinSparkle.OnDidNotFindUpdate.htm"}
,{"title":"TWinSparkle.OnError","href":"WinSparkle.TWinSparkle.OnError.htm"}
,{"title":"TWinSparkle.OnShutDown","href":"WinSparkle.TWinSparkle.OnShutDown.htm"}
,{"title":"TWinSparkle.OnUpdateCancelled","href":"WinSparkle.TWinSparkle.OnUpdateCancelled.htm"}
,{"title":"TWinSparkle.RegistryPath","href":"WinSparkle.TWinSparkle.RegistryPath.htm"}
,{"title":"TWinSparkle.ResetUpdateCheckInterval","href":"WinSparkle.TWinSparkle.ResetUpdateCheckInterval.htm"}
,{"title":"TWinSparkle.SetAppDetails(string,string,string)","href":"WinSparkle.TWinSparkle.SetAppDetails.htm"}
,{"title":"TWinSparkle.SetLang(string)","href":"WinSparkle.TWinSparkle.SetLang.htm"}
,{"title":"TWinSparkle.SetLangID(ShortInt)","href":"WinSparkle.TWinSparkle.SetLangID.htm"}
,{"title":"TWinSparkle.UpdateCheckInterval","href":"WinSparkle.TWinSparkle.UpdateCheckInterval.htm"}
,{"title":"Unit4","href":"Unit4.htm"}
,{"title":"Unit4.TForm4","href":"Unit4.TForm4.htm"}
,{"title":"WinSparkle","href":"WinSparkle.htm"}
,{"title":"WinSparkle.TCallbackArray","href":"WinSparkle.TCallbackArray.htm"}
,{"title":"WinSparkle.TCallbackArrayFunctions","href":"WinSparkle.TCallbackArrayFunctions.htm"}
,{"title":"WinSparkle.TCallbackType","href":"WinSparkle.TCallbackType.htm"}
,{"title":"WinSparkle.TCallbackTypeFunc","href":"WinSparkle.TCallbackTypeFunc.htm"}
,{"title":"WinSparkle.TUpdateType","href":"WinSparkle.TUpdateType.htm"}
,{"title":"WinSparkle.TWinSparkle","href":"WinSparkle.TWinSparkle.htm"}
,{"title":"WinSparkleLib","href":"WinSparkle.WinSparkleLib.htm"}
]