[{"title":"Project3","key":"Project3","href":"Project3.htm","activate":true,"children":[{"title":"Unit4","key":"Unit4","href":"Unit4.htm","children":[{"title":"Classes","key":"Unit4_Classes","href":"Unit4_Classes.htm","children":[{"title":"TForm4","key":"Unit4.TForm4","href":"Unit4.TForm4.htm","children":[{"title":"Methods","key":"Unit4.TForm4_Methods","href":"Unit4.TForm4_Methods.htm","children":[{"title":"Button1Click(TObject)","key":"Unit4.TForm4.Button1Click(TObject)","href":"Unit4.TForm4.Button1Click.htm"}
,{"title":"Button2Click(TObject)","key":"Unit4.TForm4.Button2Click(TObject)","href":"Unit4.TForm4.Button2Click.htm"}
,{"title":"Button3Click(TObject)","key":"Unit4.TForm4.Button3Click(TObject)","href":"Unit4.TForm4.Button3Click.htm"}
,{"title":"Button4Click(TObject)","key":"Unit4.TForm4.Button4Click(TObject)","href":"Unit4.TForm4.Button4Click.htm"}
,{"title":"Button5Click(TObject)","key":"Unit4.TForm4.Button5Click(TObject)","href":"Unit4.TForm4.Button5Click.htm"}
,{"title":"Button6Click(TObject)","key":"Unit4.TForm4.Button6Click(TObject)","href":"Unit4.TForm4.Button6Click.htm"}
,{"title":"Button7Click(TObject)","key":"Unit4.TForm4.Button7Click(TObject)","href":"Unit4.TForm4.Button7Click.htm"}
,{"title":"Button8Click(TObject)","key":"Unit4.TForm4.Button8Click(TObject)","href":"Unit4.TForm4.Button8Click.htm"}
,{"title":"Button9Click(TObject)","key":"Unit4.TForm4.Button9Click(TObject)","href":"Unit4.TForm4.Button9Click.htm"}
,{"title":"CheckBox1Change(TObject)","key":"Unit4.TForm4.CheckBox1Change(TObject)","href":"Unit4.TForm4.CheckBox1Change.htm"}
,{"title":"FormCreate(TObject)","key":"Unit4.TForm4.FormCreate(TObject)","href":"Unit4.TForm4.FormCreate.htm"}
,{"title":"FormDestroy(TObject)","key":"Unit4.TForm4.FormDestroy(TObject)","href":"Unit4.TForm4.FormDestroy.htm"}
]}
,{"title":"Fields","key":"Unit4.TForm4_Fields","href":"Unit4.TForm4_Fields.htm","children":[{"title":"Button1","key":"Unit4.TForm4.Button1","href":"Unit4.TForm4.Button1.htm"}
,{"title":"Button2","key":"Unit4.TForm4.Button2","href":"Unit4.TForm4.Button2.htm"}
,{"title":"Button3","key":"Unit4.TForm4.Button3","href":"Unit4.TForm4.Button3.htm"}
,{"title":"Button4","key":"Unit4.TForm4.Button4","href":"Unit4.TForm4.Button4.htm"}
,{"title":"Button5","key":"Unit4.TForm4.Button5","href":"Unit4.TForm4.Button5.htm"}
,{"title":"Button6","key":"Unit4.TForm4.Button6","href":"Unit4.TForm4.Button6.htm"}
,{"title":"Button7","key":"Unit4.TForm4.Button7","href":"Unit4.TForm4.Button7.htm"}
,{"title":"Button8","key":"Unit4.TForm4.Button8","href":"Unit4.TForm4.Button8.htm"}
,{"title":"Button9","key":"Unit4.TForm4.Button9","href":"Unit4.TForm4.Button9.htm"}
,{"title":"CheckBox1","key":"Unit4.TForm4.CheckBox1","href":"Unit4.TForm4.CheckBox1.htm"}
,{"title":"CheckBox2","key":"Unit4.TForm4.CheckBox2","href":"Unit4.TForm4.CheckBox2.htm"}
,{"title":"CheckBox3","key":"Unit4.TForm4.CheckBox3","href":"Unit4.TForm4.CheckBox3.htm"}
,{"title":"CheckBox4","key":"Unit4.TForm4.CheckBox4","href":"Unit4.TForm4.CheckBox4.htm"}
,{"title":"CheckBox5","key":"Unit4.TForm4.CheckBox5","href":"Unit4.TForm4.CheckBox5.htm"}
,{"title":"Circle1","key":"Unit4.TForm4.Circle1","href":"Unit4.TForm4.Circle1.htm"}
,{"title":"Edit1","key":"Unit4.TForm4.Edit1","href":"Unit4.TForm4.Edit1.htm"}
,{"title":"Edit2","key":"Unit4.TForm4.Edit2","href":"Unit4.TForm4.Edit2.htm"}
,{"title":"Edit3","key":"Unit4.TForm4.Edit3","href":"Unit4.TForm4.Edit3.htm"}
,{"title":"Edit4","key":"Unit4.TForm4.Edit4","href":"Unit4.TForm4.Edit4.htm"}
,{"title":"Edit5","key":"Unit4.TForm4.Edit5","href":"Unit4.TForm4.Edit5.htm"}
,{"title":"GroupBox1","key":"Unit4.TForm4.GroupBox1","href":"Unit4.TForm4.GroupBox1.htm"}
,{"title":"GroupBox2","key":"Unit4.TForm4.GroupBox2","href":"Unit4.TForm4.GroupBox2.htm"}
,{"title":"Label1","key":"Unit4.TForm4.Label1","href":"Unit4.TForm4.Label1.htm"}
,{"title":"Label10","key":"Unit4.TForm4.Label10","href":"Unit4.TForm4.Label10.htm"}
,{"title":"Label2","key":"Unit4.TForm4.Label2","href":"Unit4.TForm4.Label2.htm"}
,{"title":"Label3","key":"Unit4.TForm4.Label3","href":"Unit4.TForm4.Label3.htm"}
,{"title":"Label4","key":"Unit4.TForm4.Label4","href":"Unit4.TForm4.Label4.htm"}
,{"title":"Label5","key":"Unit4.TForm4.Label5","href":"Unit4.TForm4.Label5.htm"}
,{"title":"Label6","key":"Unit4.TForm4.Label6","href":"Unit4.TForm4.Label6.htm"}
,{"title":"Label7","key":"Unit4.TForm4.Label7","href":"Unit4.TForm4.Label7.htm"}
,{"title":"Label8","key":"Unit4.TForm4.Label8","href":"Unit4.TForm4.Label8.htm"}
,{"title":"Label9","key":"Unit4.TForm4.Label9","href":"Unit4.TForm4.Label9.htm"}
,{"title":"PopupBox1","key":"Unit4.TForm4.PopupBox1","href":"Unit4.TForm4.PopupBox1.htm"}
,{"title":"RadioButton1","key":"Unit4.TForm4.RadioButton1","href":"Unit4.TForm4.RadioButton1.htm"}
,{"title":"RadioButton2","key":"Unit4.TForm4.RadioButton2","href":"Unit4.TForm4.RadioButton2.htm"}
,{"title":"RadioButton3","key":"Unit4.TForm4.RadioButton3","href":"Unit4.TForm4.RadioButton3.htm"}
,{"title":"Rectangle1","key":"Unit4.TForm4.Rectangle1","href":"Unit4.TForm4.Rectangle1.htm"}
]}
]}
]}
,{"title":"Variables","key":"Unit4_Variables","href":"Unit4_Variables.htm","children":[{"title":"Form4","key":"Unit4.Form4","href":"Unit4.Form4.htm"}
]}
]}
,{"title":"WinSparkle","key":"WinSparkle","href":"WinSparkle.htm","children":[{"title":"Classes","key":"WinSparkle_Classes","href":"WinSparkle_Classes.htm","children":[{"title":"TWinSparkle","key":"WinSparkle.TWinSparkle","href":"WinSparkle.TWinSparkle.htm","children":[{"title":"Constructors","key":"WinSparkle.TWinSparkle_Constructors","href":"WinSparkle.TWinSparkle_Constructors.htm","children":[{"title":"Create","key":"WinSparkle.TWinSparkle.Create","href":"WinSparkle.TWinSparkle.Create.htm"}
,{"title":"Create(string)","key":"WinSparkle.TWinSparkle.Create(string)","href":"WinSparkle.TWinSparkle.Create(string).htm"}
,{"title":"Destroy","key":"WinSparkle.TWinSparkle.Destroy","href":"WinSparkle.TWinSparkle.Destroy.htm"}
]}
,{"title":"Properties","key":"WinSparkle.TWinSparkle_Properties","href":"WinSparkle.TWinSparkle_Properties.htm","children":[{"title":"AppBuildVersion","key":"WinSparkle.TWinSparkle.AppBuildVersion","href":"WinSparkle.TWinSparkle.AppBuildVersion.htm"}
,{"title":"AppcastURL","key":"WinSparkle.TWinSparkle.AppcastURL","href":"WinSparkle.TWinSparkle.AppcastURL.htm"}
,{"title":"AutoCheckForUpdates","key":"WinSparkle.TWinSparkle.AutoCheckForUpdates","href":"WinSparkle.TWinSparkle.AutoCheckForUpdates.htm"}
,{"title":"DLLLoaded","key":"WinSparkle.TWinSparkle.DLLLoaded","href":"WinSparkle.TWinSparkle.DLLLoaded.htm"}
,{"title":"DLLPath","key":"WinSparkle.TWinSparkle.DLLPath","href":"WinSparkle.TWinSparkle.DLLPath.htm"}
,{"title":"LastCheckTime","key":"WinSparkle.TWinSparkle.LastCheckTime","href":"WinSparkle.TWinSparkle.LastCheckTime.htm"}
,{"title":"OnCanShutDown","key":"WinSparkle.TWinSparkle.OnCanShutDown","href":"WinSparkle.TWinSparkle.OnCanShutDown.htm"}
,{"title":"OnDidFindUpdate","key":"WinSparkle.TWinSparkle.OnDidFindUpdate","href":"WinSparkle.TWinSparkle.OnDidFindUpdate.htm"}
,{"title":"OnDidNotFindUpdate","key":"WinSparkle.TWinSparkle.OnDidNotFindUpdate","href":"WinSparkle.TWinSparkle.OnDidNotFindUpdate.htm"}
,{"title":"OnError","key":"WinSparkle.TWinSparkle.OnError","href":"WinSparkle.TWinSparkle.OnError.htm"}
,{"title":"OnShutDown","key":"WinSparkle.TWinSparkle.OnShutDown","href":"WinSparkle.TWinSparkle.OnShutDown.htm"}
,{"title":"OnUpdateCancelled","key":"WinSparkle.TWinSparkle.OnUpdateCancelled","href":"WinSparkle.TWinSparkle.OnUpdateCancelled.htm"}
,{"title":"RegistryPath","key":"WinSparkle.TWinSparkle.RegistryPath","href":"WinSparkle.TWinSparkle.RegistryPath.htm"}
,{"title":"UpdateCheckInterval","key":"WinSparkle.TWinSparkle.UpdateCheckInterval","href":"WinSparkle.TWinSparkle.UpdateCheckInterval.htm"}
]}
,{"title":"Methods","key":"WinSparkle.TWinSparkle_Methods","href":"WinSparkle.TWinSparkle_Methods.htm","children":[{"title":"CheckUpdate(TUpdateType)","key":"WinSparkle.TWinSparkle.CheckUpdate(TUpdateType)","href":"WinSparkle.TWinSparkle.CheckUpdate.htm"}
,{"title":"CheckUpdateWithoutUI","key":"WinSparkle.TWinSparkle.CheckUpdateWithoutUI","href":"WinSparkle.TWinSparkle.CheckUpdateWithoutUI.htm"}
,{"title":"CheckUpdateWithUI","key":"WinSparkle.TWinSparkle.CheckUpdateWithUI","href":"WinSparkle.TWinSparkle.CheckUpdateWithUI.htm"}
,{"title":"CheckUpdateWithUIandInstall","key":"WinSparkle.TWinSparkle.CheckUpdateWithUIandInstall","href":"WinSparkle.TWinSparkle.CheckUpdateWithUIandInstall.htm"}
,{"title":"Cleanup","key":"WinSparkle.TWinSparkle.Cleanup","href":"WinSparkle.TWinSparkle.Cleanup.htm"}
,{"title":"Init","key":"WinSparkle.TWinSparkle.Init","href":"WinSparkle.TWinSparkle.Init.htm"}
,{"title":"ResetUpdateCheckInterval","key":"WinSparkle.TWinSparkle.ResetUpdateCheckInterval","href":"WinSparkle.TWinSparkle.ResetUpdateCheckInterval.htm"}
,{"title":"SetAppDetails(string,string,string)","key":"WinSparkle.TWinSparkle.SetAppDetails(string,string,string)","href":"WinSparkle.TWinSparkle.SetAppDetails.htm"}
,{"title":"SetLang(string)","key":"WinSparkle.TWinSparkle.SetLang(string)","href":"WinSparkle.TWinSparkle.SetLang.htm"}
,{"title":"SetLangID(ShortInt)","key":"WinSparkle.TWinSparkle.SetLangID(ShortInt)","href":"WinSparkle.TWinSparkle.SetLangID.htm"}
]}
]}
]}
,{"title":"Enumerations","key":"WinSparkle_Enumerations","href":"WinSparkle_Enumerations.htm","children":[{"title":"TCallbackType","key":"WinSparkle.TCallbackType","href":"WinSparkle.TCallbackType.htm"}
,{"title":"TCallbackTypeFunc","key":"WinSparkle.TCallbackTypeFunc","href":"WinSparkle.TCallbackTypeFunc.htm"}
,{"title":"TUpdateType","key":"WinSparkle.TUpdateType","href":"WinSparkle.TUpdateType.htm"}
]}
,{"title":"Types","key":"WinSparkle_Types","href":"WinSparkle_Types.htm","children":[{"title":"TCallbackArray","key":"WinSparkle.TCallbackArray","href":"WinSparkle.TCallbackArray.htm"}
,{"title":"TCallbackArrayFunctions","key":"WinSparkle.TCallbackArrayFunctions","href":"WinSparkle.TCallbackArrayFunctions.htm"}
]}
,{"title":"Variables","key":"WinSparkle_Variables","href":"WinSparkle_Variables.htm","children":[{"title":"callbackFuncs","key":"WinSparkle.callbackFuncs","href":"WinSparkle.callbackFuncs.htm"}
,{"title":"callbackProcs","key":"WinSparkle.callbackProcs","href":"WinSparkle.callbackProcs.htm"}
]}
,{"title":"Constants","key":"WinSparkle_Constants","href":"WinSparkle_Constants.htm","children":[{"title":"BugVersion","key":"WinSparkle.BugVersion","href":"WinSparkle.BugVersion.htm"}
,{"title":"MajorVersion","key":"WinSparkle.MajorVersion","href":"WinSparkle.MajorVersion.htm"}
,{"title":"MinorVersion","key":"WinSparkle.MinorVersion","href":"WinSparkle.MinorVersion.htm"}
,{"title":"WinSparkleLib","key":"WinSparkle.WinSparkleLib","href":"WinSparkle.WinSparkleLib.htm"}
]}
,{"title":"Routines","key":"WinSparkle_Routines","href":"WinSparkle_Routines.htm","children":[{"title":"DoOnCanShutdown","key":"WinSparkle.DoOnCanShutdown","href":"WinSparkle.DoOnCanShutdown.htm"}
,{"title":"DoOnError","key":"WinSparkle.DoOnError","href":"WinSparkle.DoOnError.htm"}
,{"title":"DoOnShutDown","key":"WinSparkle.DoOnShutDown","href":"WinSparkle.DoOnShutDown.htm"}
,{"title":"DoOnUpdateCancelled","key":"WinSparkle.DoOnUpdateCancelled","href":"WinSparkle.DoOnUpdateCancelled.htm"}
,{"title":"DoOnUpdateFound","key":"WinSparkle.DoOnUpdateFound","href":"WinSparkle.DoOnUpdateFound.htm"}
,{"title":"DoOnUpdateNotFound","key":"WinSparkle.DoOnUpdateNotFound","href":"WinSparkle.DoOnUpdateNotFound.htm"}
]}
]}
]}
]