#ifndef _WINSPARKLE_STRING_IDS_
#define _WINSPARKLE_STRING_IDS_

typedef enum WinSparkleStringID {
	WSS_SOFTWAREUPDATE,
	WSS_UPDATEAVAILABLE,
	WSS_RELEASENOTES,
	WSS_SKIPTHISVERSION,
	WSS_REMINDMELATER,
	WSS_INSTALLUPDATE,
	WSS_CANNOTBERESTARTED_FMT1,
	WSS_UNSAVEDDOCUMENTSTRYAGAIN,
	WSS_LAUNCHINGINSTALLER,
	WSS_FAILEDTOLAUNCHINSTALLER,
	WSS_CHECKINGFORUPDATES,
	WSS_CANCEL,
	WSS_UPTODATE,
	WSS_ISCURRENT_FMT2,
	WSS_CLOSE,
	WSS_UPDATEERROR,
	WSS_ERROROCCURRED,
	WSS_NEWVERSION_FMT1,
	WSS_GETUPDATE,
	WSS_NOWAVAILABLE_FMT3,
	WSS_DOWNLOADING,
	WSS_PROGRESSOF_FMT2,
	WSS_READYTOINSTALL,
	WSS_CHECKAUTOMATICALLYQUESTIONHEADER,
	WSS_CHECKAUTOMATICALLYQUESTION_FMT1,
	WSS_CHECKAUTOMATICALLY,
	WSS_DONTCHECK
} WinSparkleStringID;


#endif //_WINSPARKLE_STRING_IDS_
