name: Check translations

on:
  push:
    paths:
    - 'translations/*.po'
  pull_request:
    paths:
    - 'translations/*.po'

jobs:
  check-po-validity:
    name: Check translation files correctness
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Run a multi-line script
      run: |
        for i in translations/*.po ; do
          msgfmt -v -c -o /dev/null $i
        done
